# Auto-generated by scripts/generate_terraform_types.py for v26.7.0 - DO NOT EDIT MANUALLY

variable "helm_values_override" {
  description = "Override any Helm chart values for the Materialize operator. This is deep-merged with the module's default values.\n\nSee https://materialize.com/docs/installation/configuration/ for all available options."
  type = object({
    balancerd = optional(object({
      affinity = optional(object(any))
      defaultResources = optional(object({
        limits   = optional(object(any))
        requests = optional(object(any))
      }))
      enabled      = optional(bool)
      nodeSelector = optional(object(any))
      tolerations  = optional(object(any))
    }))
    clusterd = optional(object({
      affinity              = optional(object(any))
      nodeSelector          = optional(object(any))
      scratchfsNodeSelector = optional(object(any))
      swapNodeSelector      = optional(object(any))
      tolerations           = optional(object(any))
    }))
    console = optional(object({
      affinity = optional(object(any))
      defaultResources = optional(object({
        limits   = optional(object(any))
        requests = optional(object(any))
      }))
      enabled             = optional(bool)
      imageTagMapOverride = optional(object(any))
      nodeSelector        = optional(object(any))
      tolerations         = optional(object(any))
    }))
    environmentd = optional(object({
      affinity = optional(object(any))
      defaultResources = optional(object({
        limits   = optional(object(any))
        requests = optional(object(any))
      }))
      nodeSelector = optional(object(any))
      tolerations  = optional(object(any))
    }))
    networkPolicies = optional(object({
      egress = optional(object({
        cidrs   = optional(list(any))
        enabled = optional(bool)
      }))
      enabled = optional(bool)
      ingress = optional(object({
        cidrs   = optional(list(any))
        enabled = optional(bool)
      }))
      internal = optional(object({
        enabled = optional(bool)
      }))
    }))
    observability = optional(object({
      enabled = optional(bool)
      podMetrics = optional(object({
        enabled = optional(bool)
      }))
      prometheus = optional(object({
        scrapeAnnotations = optional(object({
          enabled = optional(bool)
        }))
      }))
    }))
    operator = optional(object({
      additionalMaterializeCRDColumns = optional(object(any))
      affinity                        = optional(object(any))
      args = optional(object({
        enableInternalStatementLogging = optional(bool)
        enableLicenseKeyChecks         = optional(bool)
        startupLogFilter               = optional(any)
      }))
      cloudProvider = optional(object({
        providers = optional(object({
          aws = optional(object({
            accountID = optional(any)
            enabled   = optional(bool)
            iam = optional(object({
              roles = optional(object({
                connection  = optional(any)
                environment = optional(any)
              }))
            }))
          }))
          gcp = optional(object(any))
        }))
        region = optional(any)
        type   = optional(any)
      }))
      clusters = optional(object({
        defaultReplicationFactor = optional(object({
          analytics = optional(number)
          probe     = optional(number)
          support   = optional(number)
          system    = optional(number)
        }))
        defaultSizes = optional(object({
          analytics     = optional(any)
          catalogServer = optional(any)
          default       = optional(any)
          probe         = optional(any)
          support       = optional(any)
          system        = optional(any)
        }))
        swap_enabled = optional(bool)
      }))
      image = optional(object({
        pullPolicy = optional(any)
        repository = optional(any)
        tag        = optional(any)
      }))
      nodeSelector = optional(object(any))
      resources = optional(object({
        limits   = optional(object(any))
        requests = optional(object(any))
      }))
      secretsController = optional(any)
      tolerations       = optional(object(any))
    }))
    rbac = optional(object({
      create = optional(bool)
    }))
    schedulerName = optional(any)
    serviceAccount = optional(object({
      create = optional(bool)
      name   = optional(any)
    }))
    storage = optional(object({
      storageClass = optional(object({
        allowVolumeExpansion = optional(bool)
        create               = optional(bool)
        name                 = optional(any)
        parameters           = optional(object(any))
        provisioner          = optional(any)
        reclaimPolicy        = optional(any)
        volumeBindingMode    = optional(any)
      }))
    }))
    telemetry = optional(object({
      enabled           = optional(bool)
      segmentApiKey     = optional(any)
      segmentClientSide = optional(bool)
    }))
    tls = optional(object({
      defaultCertificateSpecs = optional(object(any))
    }))
  })
  default  = {}
  nullable = false
}

variable "materialize_spec_override" {
  description = "Override any field in the Materialize CRD spec. This is deep-merged with the module's default spec.\n\nSee https://materialize.com/docs/installation/appendix-materialize-crd-field-descriptions/ for all available fields."
  type = object({
    environmentdImageRef = optional(string)
    authenticatorKind    = optional(string)
    balancerdExternalCertificateSpec = optional(object({
      dnsNames = optional(list(string))
      duration = optional(string)
      issuerRef = optional(object({
        name  = string
        group = optional(string)
        kind  = optional(string)
      }))
      renewBefore = optional(string)
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    balancerdReplicas = optional(number)
    balancerdResourceRequirements = optional(object({
      claims = optional(list(object({
        name    = string
        request = optional(string)
      })))
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    consoleExternalCertificateSpec = optional(object({
      dnsNames = optional(list(string))
      duration = optional(string)
      issuerRef = optional(object({
        name  = string
        group = optional(string)
        kind  = optional(string)
      }))
      renewBefore = optional(string)
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    consoleReplicas = optional(number)
    consoleResourceRequirements = optional(object({
      claims = optional(list(object({
        name    = string
        request = optional(string)
      })))
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    enableRbac                    = optional(bool)
    environmentId                 = optional(string)
    environmentdConnectionRoleArn = optional(string)
    environmentdExtraArgs         = optional(list(string))
    environmentdExtraEnv = optional(list(object({
      name  = string
      value = optional(string)
      valueFrom = optional(object({
        configMapKeyRef = optional(object({
          key      = string
          name     = string
          optional = optional(bool)
        }))
        fieldRef = optional(object({
          fieldPath  = string
          apiVersion = optional(string)
        }))
        resourceFieldRef = optional(object({
          resource      = string
          containerName = optional(string)
          divisor       = optional(string)
        }))
        secretKeyRef = optional(object({
          key      = string
          name     = string
          optional = optional(bool)
        }))
      }))
    })))
    environmentdResourceRequirements = optional(object({
      claims = optional(list(object({
        name    = string
        request = optional(string)
      })))
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    environmentdScratchVolumeStorageRequirement = optional(string)
    forcePromote                                = optional(string)
    forceRollout                                = optional(string)
    internalCertificateSpec = optional(object({
      dnsNames = optional(list(string))
      duration = optional(string)
      issuerRef = optional(object({
        name  = string
        group = optional(string)
        kind  = optional(string)
      }))
      renewBefore = optional(string)
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    podAnnotations               = optional(map(string))
    podLabels                    = optional(map(string))
    requestRollout               = optional(string)
    rolloutStrategy              = optional(string)
    serviceAccountAnnotations    = optional(map(string))
    serviceAccountLabels         = optional(map(string))
    serviceAccountName           = optional(string)
    systemParameterConfigmapName = optional(string)
  })
  default  = {}
  nullable = false
}
