# Auto-generated by scripts/generate_terraform_types.py for v26.7.0 - DO NOT EDIT MANUALLY

variable "helm_values" {
  description = "Additional values to pass to the Helm chart. This is deep-merged with the module's default values.\n\nSee https://materialize.com/docs/installation/configuration/ for all available options."
  type = object({
    balancerd = optional(object({
      affinity = optional(any)
      defaultResources = optional(object({
        limits   = optional(any)
        requests = optional(any)
      }))
      enabled      = optional(bool)
      nodeSelector = optional(any)
      tolerations  = optional(any)
    }))
    clusterd = optional(object({
      affinity              = optional(any)
      nodeSelector          = optional(any)
      scratchfsNodeSelector = optional(any)
      swapNodeSelector      = optional(any)
      tolerations           = optional(any)
    }))
    console = optional(object({
      affinity = optional(any)
      defaultResources = optional(object({
        limits   = optional(any)
        requests = optional(any)
      }))
      enabled             = optional(bool)
      imageTagMapOverride = optional(any)
      nodeSelector        = optional(any)
      tolerations         = optional(any)
    }))
    environmentd = optional(object({
      affinity = optional(any)
      defaultResources = optional(object({
        limits   = optional(any)
        requests = optional(any)
      }))
      nodeSelector = optional(any)
      tolerations  = optional(any)
    }))
    networkPolicies = optional(object({
      egress = optional(object({
        cidrs   = optional(any)
        enabled = optional(bool)
      }))
      enabled = optional(bool)
      ingress = optional(object({
        cidrs   = optional(any)
        enabled = optional(bool)
      }))
      internal = optional(object({
        enabled = optional(bool)
      }))
    }))
    observability = optional(object({
      enabled = optional(bool)
      podMetrics = optional(object({
        enabled = optional(bool)
      }))
      prometheus = optional(object({
        scrapeAnnotations = optional(object({
          enabled = optional(bool)
        }))
      }))
    }))
    operator = optional(object({
      additionalMaterializeCRDColumns = optional(any)
      affinity                        = optional(any)
      args = optional(object({
        enableInternalStatementLogging = optional(bool)
        enableLicenseKeyChecks         = optional(bool)
        startupLogFilter               = optional(any)
      }))
      cloudProvider = optional(object({
        providers = optional(object({
          aws = optional(object({
            accountID = optional(any)
            enabled   = optional(bool)
            iam = optional(object({
              roles = optional(object({
                connection  = optional(any)
                environment = optional(any)
              }))
            }))
          }))
          gcp = optional(any)
        }))
        region = optional(any)
        type   = optional(any)
      }))
      clusters = optional(object({
        defaultReplicationFactor = optional(object({
          analytics = optional(number)
          probe     = optional(number)
          support   = optional(number)
          system    = optional(number)
        }))
        defaultSizes = optional(object({
          analytics     = optional(any)
          catalogServer = optional(any)
          default       = optional(any)
          probe         = optional(any)
          support       = optional(any)
          system        = optional(any)
        }))
        swap_enabled = optional(bool)
      }))
      image = optional(object({
        pullPolicy = optional(any)
        repository = optional(any)
        tag        = optional(any)
      }))
      nodeSelector = optional(any)
      resources = optional(object({
        limits   = optional(any)
        requests = optional(any)
      }))
      secretsController = optional(any)
      tolerations       = optional(any)
    }))
    rbac = optional(object({
      create = optional(bool)
    }))
    schedulerName = optional(any)
    serviceAccount = optional(object({
      create = optional(bool)
      name   = optional(any)
    }))
    storage = optional(object({
      storageClass = optional(object({
        allowVolumeExpansion = optional(bool)
        create               = optional(bool)
        name                 = optional(any)
        parameters           = optional(any)
        provisioner          = optional(any)
        reclaimPolicy        = optional(any)
        volumeBindingMode    = optional(any)
      }))
    }))
    telemetry = optional(object({
      enabled           = optional(bool)
      segmentApiKey     = optional(any)
      segmentClientSide = optional(bool)
    }))
    tls = optional(object({
      defaultCertificateSpecs = optional(any)
    }))
  })
  default  = {}
  nullable = false
}
