# Auto-generated by scripts/generate_terraform_types.py
# DO NOT EDIT MANUALLY - changes will be overwritten

variable "materialize_spec_override" {
  description = <<-EOT
    Override any field in the Materialize CRD spec. This is deep-merged with the default spec
    built from other variables, allowing you to set any CRD field not exposed as a dedicated variable.

    See https://materialize.com/docs/installation/appendix-materialize-crd-field-descriptions/ for all available fields.
  EOT

  type = object({
    authenticatorKind = optional(string)
    balancerdExternalCertificateSpec = optional(object({
      dnsNames    = optional(list(string))
      duration    = optional(string)
      renewBefore = optional(string)
      issuerRef = optional(object({
        name  = string
        kind  = optional(string)
        group = optional(string)
      }))
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    balancerdReplicas = optional(number)
    balancerdResourceRequirements = optional(object({
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    consoleExternalCertificateSpec = optional(object({
      dnsNames    = optional(list(string))
      duration    = optional(string)
      renewBefore = optional(string)
      issuerRef = optional(object({
        name  = string
        kind  = optional(string)
        group = optional(string)
      }))
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    consoleReplicas = optional(number)
    consoleResourceRequirements = optional(object({
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    enableRbac                    = optional(bool)
    environmentId                 = optional(string)
    environmentdConnectionRoleArn = optional(string)
    environmentdExtraArgs         = optional(list(string))
    environmentdExtraEnv = optional(list(object({
      name      = string
      value     = optional(string)
      valueFrom = optional(any)
    })))
    environmentdResourceRequirements = optional(object({
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    environmentdScratchVolumeStorageRequirement = optional(string)
    forcePromote                                = optional(string)
    forceRollout                                = optional(string)
    internalCertificateSpec = optional(object({
      dnsNames    = optional(list(string))
      duration    = optional(string)
      renewBefore = optional(string)
      issuerRef = optional(object({
        name  = string
        kind  = optional(string)
        group = optional(string)
      }))
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    podAnnotations            = optional(map(string))
    podLabels                 = optional(map(string))
    requestRollout            = optional(string)
    rolloutStrategy           = optional(string)
    serviceAccountAnnotations = optional(map(string))
    serviceAccountLabels      = optional(map(string))
    serviceAccountName        = optional(string)
  })

  default  = {}
  nullable = false
}
