# Auto-generated by scripts/generate_terraform_types.py for v26.7.0 - DO NOT EDIT MANUALLY

variable "materialize_spec_override" {
  description = "Override any field in the Materialize CRD spec. This is deep-merged with the default spec built from other variables, allowing you to set any CRD field not exposed as a dedicated variable.\n\nSee https://materialize.com/docs/installation/appendix-materialize-crd-field-descriptions/ for all available fields."
  type = object({
    environmentdImageRef = optional(string)
    authenticatorKind    = optional(string)
    balancerdExternalCertificateSpec = optional(object({
      dnsNames = optional(list(string))
      duration = optional(string)
      issuerRef = optional(object({
        name  = string
        group = optional(string)
        kind  = optional(string)
      }))
      renewBefore = optional(string)
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    balancerdReplicas = optional(number)
    balancerdResourceRequirements = optional(object({
      claims = optional(list(object({
        name    = string
        request = optional(string)
      })))
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    consoleExternalCertificateSpec = optional(object({
      dnsNames = optional(list(string))
      duration = optional(string)
      issuerRef = optional(object({
        name  = string
        group = optional(string)
        kind  = optional(string)
      }))
      renewBefore = optional(string)
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    consoleReplicas = optional(number)
    consoleResourceRequirements = optional(object({
      claims = optional(list(object({
        name    = string
        request = optional(string)
      })))
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    enableRbac                    = optional(bool)
    environmentId                 = optional(string)
    environmentdConnectionRoleArn = optional(string)
    environmentdExtraArgs         = optional(list(string))
    environmentdExtraEnv = optional(list(object({
      name  = string
      value = optional(string)
      valueFrom = optional(object({
        configMapKeyRef = optional(object({
          key      = string
          name     = string
          optional = optional(bool)
        }))
        fieldRef = optional(object({
          fieldPath  = string
          apiVersion = optional(string)
        }))
        resourceFieldRef = optional(object({
          resource      = string
          containerName = optional(string)
          divisor       = optional(string)
        }))
        secretKeyRef = optional(object({
          key      = string
          name     = string
          optional = optional(bool)
        }))
      }))
    })))
    environmentdResourceRequirements = optional(object({
      claims = optional(list(object({
        name    = string
        request = optional(string)
      })))
      limits   = optional(map(string))
      requests = optional(map(string))
    }))
    environmentdScratchVolumeStorageRequirement = optional(string)
    forcePromote                                = optional(string)
    forceRollout                                = optional(string)
    internalCertificateSpec = optional(object({
      dnsNames = optional(list(string))
      duration = optional(string)
      issuerRef = optional(object({
        name  = string
        group = optional(string)
        kind  = optional(string)
      }))
      renewBefore = optional(string)
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    podAnnotations               = optional(map(string))
    podLabels                    = optional(map(string))
    requestRollout               = optional(string)
    rolloutStrategy              = optional(string)
    serviceAccountAnnotations    = optional(map(string))
    serviceAccountLabels         = optional(map(string))
    serviceAccountName           = optional(string)
    systemParameterConfigmapName = optional(string)
  })
  default  = {}
  nullable = false
}
