# Auto-generated by scripts/generate_terraform_types.py
# DO NOT EDIT MANUALLY - changes will be overwritten

variable "helm_values" {
  description = <<-EOT
    Additional values to pass to the Helm chart. This is deep-merged with the module's default values.
    See https://materialize.com/docs/installation/configuration/ for all available options.
  EOT

  type = object({
    operator = optional(object({
      image = optional(map(string))
      args = optional(object({
        startupLogFilter               = optional(string)
        enableInternalStatementLogging = optional(bool)
        enableLicenseKeyChecks         = optional(bool)
      }))
      additionalMaterializeCRDColumns = optional(any)
      cloudProvider = optional(object({
        type   = optional(string)
        region = optional(string)
        providers = optional(object({
          aws = optional(object({
            enabled   = optional(bool)
            accountID = optional(string)
            iam = optional(object({
              roles = optional(map(string))
            }))
          }))
          gcp = optional(map(bool))
        }))
      }))
      clusters = optional(object({
        swap_enabled = optional(bool)
        sizes = optional(map(object({
          workers          = optional(number)
          scale            = optional(number)
          cpu_exclusive    = optional(bool)
          cpu_limit        = optional(number)
          credits_per_hour = optional(string)
          disk_limit       = optional(string)
          memory_limit     = optional(string)
        })))
        defaultSizes             = optional(map(string))
        defaultReplicationFactor = optional(map(number))
      }))
      nodeSelector = optional(any)
      affinity     = optional(any)
      tolerations  = optional(any)
      resources = optional(object({
        requests = optional(map(string))
        limits   = optional(map(string))
      }))
      secretsController = optional(string)
    }))
    environmentd = optional(object({
      nodeSelector = optional(map(any))
      affinity     = optional(any)
      tolerations  = optional(any)
      defaultResources = optional(object({
        limits   = optional(map(string))
        requests = optional(map(string))
      }))
    }))
    clusterd = optional(object({
      nodeSelector          = optional(map(any))
      scratchfsNodeSelector = optional(map(string))
      swapNodeSelector      = optional(map(string))
      affinity              = optional(any)
      tolerations           = optional(any)
    }))
    balancerd = optional(object({
      enabled      = optional(bool)
      nodeSelector = optional(any)
      affinity     = optional(any)
      tolerations  = optional(any)
      defaultResources = optional(object({
        limits   = optional(map(string))
        requests = optional(map(string))
      }))
    }))
    console = optional(object({
      enabled             = optional(bool)
      imageTagMapOverride = optional(map(any))
      nodeSelector        = optional(any)
      affinity            = optional(any)
      tolerations         = optional(any)
      defaultResources = optional(object({
        limits   = optional(map(string))
        requests = optional(map(string))
      }))
    }))
    rbac          = optional(map(bool))
    schedulerName = optional(any)
    serviceAccount = optional(object({
      create = optional(bool)
      name   = optional(string)
    }))
    observability = optional(object({
      enabled    = optional(bool)
      podMetrics = optional(map(bool))
      prometheus = optional(object({
        scrapeAnnotations = optional(map(bool))
      }))
    }))
    telemetry = optional(object({
      enabled           = optional(bool)
      segmentApiKey     = optional(string)
      segmentClientSide = optional(bool)
    }))
    networkPolicies = optional(object({
      enabled  = optional(bool)
      internal = optional(map(bool))
      ingress = optional(object({
        enabled = optional(bool)
        cidrs   = optional(list(string))
      }))
      egress = optional(object({
        enabled = optional(bool)
        cidrs   = optional(list(string))
      }))
    }))
    tls = optional(object({
      defaultCertificateSpecs = optional(map(any))
    }))
    storage = optional(object({
      storageClass = optional(object({
        create               = optional(bool)
        name                 = optional(string)
        provisioner          = optional(string)
        parameters           = optional(map(string))
        allowVolumeExpansion = optional(bool)
        reclaimPolicy        = optional(string)
        volumeBindingMode    = optional(string)
      }))
    }))
  })

  default  = {}
  nullable = false
}
