# Auto-generated by scripts/generate_terraform_types.py for test - DO NOT EDIT MANUALLY

variable "helm_values" {
  description = "Additional values to pass to the Helm chart. This is deep-merged with the module's default values.\n\nSee https://materialize.com/docs/installation/configuration/ for all available options."
  type = object({
    operator = optional(object({
      image = optional(object({
        repository = optional(any)
        tag        = optional(any)
        pullPolicy = optional(any)
      }))
      args = optional(object({
        enableLicenseKeyChecks = optional(bool)
        startupLogFilter       = optional(any)
      }))
      replicas     = optional(number)
      tolerations  = optional(any)
      nodeSelector = optional(any)
      clusters = optional(object({
        sizes = optional(map(object({
          workers = optional(number)
          scale   = optional(number)
        })))
        swap_enabled = optional(bool)
      }))
    }))
    balancerd = optional(object({
      enabled  = optional(bool)
      replicas = optional(number)
    }))
    environmentd = optional(object({
      resources = optional(object({
        limits = optional(object({
          memory = optional(any)
        }))
        requests = optional(object({
          cpu = optional(any)
        }))
      }))
    }))
    networkPolicies = optional(object({
      enabled = optional(bool)
      ingress = optional(object({
        enabled = optional(bool)
      }))
    }))
  })
  default  = {}
  nullable = false
}
