# Auto-generated by scripts/generate_terraform_types.py for test - DO NOT EDIT MANUALLY

variable "materialize_spec_override" {
  description = "Override any field in the Materialize CRD spec. This is deep-merged with the default spec built from other variables, allowing you to set any CRD field not exposed as a dedicated variable.\n\nSee https://materialize.com/docs/installation/appendix-materialize-crd-field-descriptions/ for all available fields."
  type = object({
    environmentdImageRef = optional(string)
    authenticatorKind    = optional(string)
    enableRbac           = optional(bool)
    balancerdReplicas    = optional(number)
    environmentdExtraArgs = optional(list(string))
    podLabels             = optional(map(string))
    internalCertificateSpec = optional(object({
      dnsNames    = optional(list(string))
      duration    = optional(string)
      renewBefore = optional(string)
      issuerRef = optional(object({
        name  = string
        kind  = optional(string)
        group = optional(string)
      }))
      secretTemplate = optional(object({
        annotations = optional(map(string))
        labels      = optional(map(string))
      }))
    }))
    environmentdResourceRequirements = optional(object({
      limits   = optional(map(string))
      requests = optional(map(string))
      claims = optional(list(object({
        name    = string
        request = optional(string)
      })))
    }))
    environmentdExtraEnv = optional(list(object({
      name  = string
      value = optional(string)
      valueFrom = optional(object({
        configMapKeyRef = optional(object({
          name     = string
          key      = string
          optional = optional(bool)
        }))
        secretKeyRef = optional(object({
          name     = string
          key      = string
          optional = optional(bool)
        }))
      }))
    })))
  })
  default  = {}
  nullable = false
}
