{
 "title": "Environment overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Materialize Instance Namespace",
    "query": {
     "query": "label_values(materialize_cloud_organization_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Replicas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "(mz_compute_cluster_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(time() - container_start_time_seconds{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Container Memory as % of Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\"}) / sum by (pod) (container_spec_memory_limit_bytes{namespace=\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Container Disk as % of Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max by (pod) (\n    container_memory_swap{namespace=~\"$namespace\"}\n    / container_spec_memory_swap_limit_bytes{namespace=~\"$namespace\"}    \n)) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Container CPU as % of Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod) /\nsum(container_spec_cpu_quota{namespace=\"$namespace\"}/container_spec_cpu_period{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Source Health - Rate Of Updates Committed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(mz_source_updates_committed{materialize_cloud_organization_namespace=\"$namespace\"}[$__rate_interval])) by (source_id)\n+ on (source_id) group_left (label2)    \n (0 * sum(label_replace(   \n    sum_over_time(mz_object_id{materialize_cloud_organization_namespace=\"$namespace\",}[$__rate_interval]),\"source_id\",\"$1\",\"label1\",\"(.*)\")) by (source_id, label2))",
     "legendFormat": "{{label2}}"
    }
   ]
  },
  {
   "title": "Source Health - Offset Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(mz_source_offset_known-mz_source_offset_committed{materialize_cloud_organization_namespace=\"$namespace\"}) by (source_id)\n+ on (source_id) group_left (label2)    \n (0 * sum(label_replace(   \n    sum_over_time(mz_object_id{materialize_cloud_organization_namespace=\"$namespace\"}[$__rate_interval]),\"source_id\",\"$1\",\"label1\",\"(.*)\")) by (source_id, label2))\n",
     "legendFormat": "{{label2}}"
    }
   ]
  },
  {
   "title": "Sink Health - Uncommitted Messages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(mz_sink_messages_staged-mz_sink_messages_committed{materialize_cloud_organization_namespace=\"$namespace\"}) by (sink_id)\n+ on (sink_id) group_left (label2)    \n (0 * sum(label_replace(   \n    sum_over_time(mz_object_id{materialize_cloud_organization_namespace=\"$namespace\"}[5m]),\"sink_id\",\"$1\",\"label1\",\"(.*)\")) by (sink_id, label2))",
     "legendFormat": "{{label2}}"
    }
   ]
  },
  {
   "title": "Source Hydration Time in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "(max ((max by (source_id) (mz_source_rehydration_latency_ms{materialize_cloud_organization_namespace=\"$namespace\",source_id=~\"u.*\"}))\n+ on (source_id) group_left (label2)    \n  sum(label_replace(   \n    mz_object_id{materialize_cloud_organization_namespace=\"$namespace\"},\"source_id\",\"$1\",\"label1\",\"(.*)\")) by (source_id, label2))\n by (label2,source_id))/1000",
     "legendFormat": "{{label2}}"
    }
   ]
  }
 ]
}