{
 "title": "Freshness",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(materialize_cloud_organization_namespace)"
    }
   },
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", instance_id=~\"u.*\", collection_id=~\"u.*\", replica_id=~\"u.*\"},instance_id)"
    }
   },
   {
    "name": "replica_id",
    "label": "replica_id",
    "query": {
     "query": "label_values(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", instance_id=~\"$cluster_id\", collection_id=~\"u.*\"},replica_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Replicas",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(mz_compute_cluster_status{ materialize_cloud_organization_namespace=\"$namespace\",compute_cluster_id=~\"u.*\"})"
    }
   ]
  },
  {
   "title": "Cluster Replica Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\".*cluster-u.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Cluster Overview for $OrgName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Progressing Objects in $cluster_name",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 8 },
   "repeat": "cluster_name",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "min((v2_mz_write_frontiers{namespace=\"$namespace\"}) \n+ on (collection_id) group_left (name, type)\n\n(0*(increase(\n(min(v2_mz_write_frontiers{namespace=\"$namespace\"}\n+ on (collection_id) group_left (cluster_id, cluster_name, name, type)    \n (0* (v2_mz_production_object{workload_class=\"production\", namespace=\"$namespace\", cluster_name=\"$cluster_name\"}))) \nby (collection_id, cluster_id, cluster_name, name, type))\n[10m:1m])>0))) by (name, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds of dataflow wallclock lag for $cluster_name by collection",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 18, "x": 6, "y": 8 },
   "repeat": "cluster_name",
   "targets": [
    {
     "expr": "(max by(namespace, instance_id, replica_id, materialize_cloud_generation,mz_context_org_name, collection_id) (mz_dataflow_wallclock_lag_seconds{quantile=\"1\", namespace=~\"$namespace\"}))\n\n+ on (namespace, instance_id, collection_id) group_left (cluster_name, name, type)\n\n(0*\nsum by(namespace, instance_id, cluster_name, collection_id, name, type)\n(label_replace(v2_mz_production_object{namespace=~\"$namespace\", cluster_name=\"$cluster_name\"},\"instance_id\", \"$1\", \"cluster_id\", \"(.*)\"))\n\n)",
     "legendFormat": "replica-{{replica_id}}-gen{{materialize_cloud_generation}} | {{collection_id}}-{{name}}"
    }
   ]
  },
  {
   "title": "Current Maximum Wallclock Lag by Cluster, Replica, Generation",
   "type": "bargauge",
   "description": "*most recent w/I time range\n*missing replica ids indicate compute storage collections",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max by(materialize_cloud_organization_namespace, instance_id, replica_id, materialize_cloud_generation,mz_context_org_name) (mz_dataflow_wallclock_lag_seconds{quantile=\"1\", materialize_cloud_organization_namespace=\"$namespace\", instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\"}))\n\n+ on (materialize_cloud_organization_namespace, instance_id) group_left (compute_cluster_name)\n(0*\nsum by(materialize_cloud_organization_namespace, instance_id, compute_cluster_name)\n(label_replace(mz_compute_cluster_status{materialize_cloud_organization_namespace=~\"$namespace\"},\"instance_id\", \"$1\", \"compute_cluster_id\", \"(.*)\"))\n)\n\nor on (materialize_cloud_organization_namespace, instance_id )\n\n(max by(materialize_cloud_organization_namespace, instance_id, replica_id, materialize_cloud_generation,mz_context_org_name) (mz_dataflow_wallclock_lag_seconds{quantile=\"1\", materialize_cloud_organization_namespace=\"$namespace\", instance_id=~\".*u.*\", instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\"}))",
     "legendFormat": "{{instance_id}}-{{compute_cluster_name}}-{{replica_id}}"
    }
   ]
  },
  {
   "title": "% of Collections by Lag - replica $replica_id",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "repeat": "replica_id",
   "targets": [
    {
     "expr": "count(\n    label_replace(\n      max(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", collection_id=~\".*u.*\",instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\", quantile=\"1\"}) by (materialize_cloud_organization_namespace, instance_id, replica_id, collection_id) <= 2, \"bucket\", \"0-2s\", \"\", \"\"\n    ) \n    or \n    label_replace(\n      max(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", collection_id=~\".*u.*\",instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\", quantile=\"1\"}) by (materialize_cloud_organization_namespace, instance_id, replica_id, collection_id) > 2 and max(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", collection_id=~\".*u.*\",instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\", quantile=\"1\"}) by (materialize_cloud_organization_namespace, instance_id, replica_id, collection_id) <= 5, \"bucket\", \"2-5s\", \"\", \"\"\n    )\n    or \n    label_replace(\n      max(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", collection_id=~\".*u.*\",instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\", quantile=\"1\"}) by (materialize_cloud_organization_namespace, instance_id, replica_id, collection_id) > 5 and max(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", collection_id=~\".*u.*\",instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\", quantile=\"1\"}) by (materialize_cloud_organization_namespace, instance_id, replica_id, collection_id) <= 60, \"bucket\", \"5-60s\", \"\", \"\"\n    )\n     or \n    label_replace(\n      max(mz_dataflow_wallclock_lag_seconds{materialize_cloud_organization_namespace=\"$namespace\", collection_id=~\".*u.*\",instance_id=~\"$cluster_id\", replica_id=~\"$replica_id\", quantile=\"1\"}) by (materialize_cloud_organization_namespace, instance_id, replica_id, collection_id) > 60, \"bucket\", \"60s+\", \"\", \"\"\n    )\n\n) by (materialize_cloud_organization_namespace, bucket, instance_id, replica_id)",
     "legendFormat": "{{replica_id}} - {{bucket}}"
    }
   ]
  },
  { "title": "Wallclock Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Progressing Objects in $cluster_name",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 12, "x": 12, "y": 27 },
   "repeat": "cluster_name",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "min((v2_mz_write_frontiers{namespace=\"$namespace\"}) \n+ on (collection_id) group_left (name, type)\n\n(0*(increase(\n(min(v2_mz_write_frontiers{namespace=\"$namespace\"}\n+ on (collection_id) group_left (cluster_id, cluster_name, name, type)    \n (0* (v2_mz_production_object{workload_class=\"production\", namespace=\"$namespace\", cluster_name=\"$cluster_name\"}))) \nby (collection_id, cluster_id, cluster_name, name, type))\n[10m:1m])>0))) by (name, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Progressing Objects in $cluster_name",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 12, "x": 12, "y": 27 },
   "repeat": "cluster_name",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "min((v2_mz_write_frontiers{namespace=\"$namespace\"}) \n+ on (collection_id) group_left (name, type)\n\n(0*(increase(\n(min(v2_mz_write_frontiers{namespace=\"$namespace\"}\n+ on (collection_id) group_left (cluster_id, cluster_name, name, type)    \n (0* (v2_mz_production_object{workload_class=\"production\", namespace=\"$namespace\", cluster_name=\"$cluster_name\"}))) \nby (collection_id, cluster_id, cluster_name, name, type))\n[10m:1m])==0))) by (name, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum seconds of dataflow wallclock lag for $replica_id",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "repeat": "replica_id",
   "targets": [
    {
     "expr": "(max by(materialize_cloud_organization_namespace, instance_id, replica_id) (mz_dataflow_wallclock_lag_seconds{quantile=\"1\", materialize_cloud_organization_namespace=\"$namespace\", replica_id=~\"$replica_id\"}))\n\n+ on (materialize_cloud_organization_namespace, instance_id) group_left (compute_cluster_name)\n(0*\nsum by(materialize_cloud_organization_namespace, instance_id, compute_cluster_name)\n(label_replace(mz_compute_cluster_status{materialize_cloud_organization_namespace=~\"$namespace\"},\"instance_id\", \"$1\", \"compute_cluster_id\", \"(.*)\"))\n)\n",
     "legendFormat": "{{compute_cluster_name - {{instance_id}}-{{replica_id}}"
    }
   ]
  },
  {
   "title": "Seconds of dataflow wallclock lag for $replica_id by object",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 28 },
   "repeat": "replica_id",
   "targets": [
    {
     "expr": "(max by(materialize_cloud_organization_namespace, instance_id, replica_id,  collection_id) (mz_dataflow_wallclock_lag_seconds{quantile=\"1\", materialize_cloud_organization_namespace=~\"$namespace\", instance_id=~\"$cluster_id\",replica_id=~\"$replica_id\"}))\n\n+ on (collection_id) group_left (label2)\n0 *\nmax by(collection_id, label2) (\n    label_replace(mz_object_id{materialize_cloud_organization_namespace=~\"$namespace\"}, \"collection_id\", \"$1\", \"label1\", \"(.*)\")\n)",
     "legendFormat": "replica-{{replica_id}} | {{collection_id}}-{{label2}}"
    }
   ]
  }
 ]
}